server {
    listen 80;
    server_name localhost;

    root /var/www/html;
    index index.php;

    # BROKEN / SHALLOW HEALTH CHECK
    #
    # This deliberately reproduces the production problem.
    # NGINX returns 200 without talking to PHP-FPM.
    location = /api/check.html {
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME /var/www/html/health.php;
    fastcgi_pass php:9000;
}

    # Real PHP health check
    location = /api/health.php {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/health.php;
        fastcgi_pass php:9000;
    }

    # Simulated API request
    location = /api/ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/index.php;
        fastcgi_pass php:9000;
    }
}
