name: Trivy Security Scan

on:
  push:
    branches:
      - main


jobs:

  security-scan:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master

        with:

          image-ref: postgres:17-alpine
          
          # Only check HIGH and CRITICAL vulnerabilities
          severity: HIGH,CRITICAL
          
          # Ignore vulnerabilities that do not have fixes available
          ignore-unfixed: true
          
          # Fail workflow if fixable HIGH or CRITICAL issues are found
          exit-code: 1